<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 016 16.10.18
 * Time: 21:37
 */
$good = $sk['good'];
?>




<div itemscope="" itemtype="https://schema.org/Product">
    <meta itemprop="url" content="https://ld-prestashop.template-help.com/prestashop_64388/index.php?id_product=27&amp;controller=product&amp;id_lang=3" property="">
    <div class="primary_block row">

        <!-- left infos-->
        <div class="pb-left-column col-xs-12 col-md-6">
            <!-- product img-->
            <div id="image-block" class="clearfix is_caroucel" style="margin-left: 102.533px;">
                  <span class="view_full_size">
            <img id="bigpic" itemprop="image" src="https://ld-prestashop.template-help.com/prestashop_64388/img/p/1/4/3/143-tm_large_default.jpg" title="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" alt="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" width="800" height="1000">
          </span>
            </div> <!-- end image-block -->

            <!-- thumbnails -->
            <div id="views_block" class="clearfix">
                <a id="view_scroll_left" class="" title="Other views" href="javascript:{}" style="cursor: default; opacity: 0; display: none;"></a>
                <div id="thumbs_list" style="height: 551.833px;">
                    <ul id="thumbs_list_frame" style="width: 82.5333px; height: 676px;">
                        <li id="thumbnail_143">
                            <a href="https://ld-prestashop.template-help.com/prestashop_64388/img/p/1/4/3/143-tm_thickbox_default.jpg" data-fancybox-group="other-views" class="fancybox shown" title="Whole-Spice-Nutmeg-Whole,-1.1-Ounce">
                                <img class="img-responsive" id="thumb_143" src="https://ld-prestashop.template-help.com/prestashop_64388/img/p/1/4/3/143-medium_default.jpg" alt="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" title="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" height="203" width="162" itemprop="image">
                            </a>
                        </li>
                        <li id="thumbnail_144">
                            <a href="https://ld-prestashop.template-help.com/prestashop_64388/img/p/1/4/4/144-tm_thickbox_default.jpg" data-fancybox-group="other-views" class="fancybox" title="Whole-Spice-Nutmeg-Whole,-1.1-Ounce">
                                <img class="img-responsive" id="thumb_144" src="https://ld-prestashop.template-help.com/prestashop_64388/img/p/1/4/4/144-medium_default.jpg" alt="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" title="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" height="203" width="162" itemprop="image">
                            </a>
                        </li>
                        <li id="thumbnail_145">
                            <a href="https://ld-prestashop.template-help.com/prestashop_64388/img/p/1/4/5/145-tm_thickbox_default.jpg" data-fancybox-group="other-views" class="fancybox" title="Whole-Spice-Nutmeg-Whole,-1.1-Ounce">
                                <img class="img-responsive" id="thumb_145" src="https://ld-prestashop.template-help.com/prestashop_64388/img/p/1/4/5/145-medium_default.jpg" alt="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" title="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" height="203" width="162" itemprop="image">
                            </a>
                        </li>
                        <li id="thumbnail_146">
                            <a href="https://ld-prestashop.template-help.com/prestashop_64388/img/p/1/4/6/146-tm_thickbox_default.jpg" data-fancybox-group="other-views" class="fancybox" title="Whole-Spice-Nutmeg-Whole,-1.1-Ounce">
                                <img class="img-responsive" id="thumb_146" src="https://ld-prestashop.template-help.com/prestashop_64388/img/p/1/4/6/146-medium_default.jpg" alt="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" title="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" height="203" width="162" itemprop="image">
                            </a>
                        </li>
                        <li id="thumbnail_147">
                            <a href="https://ld-prestashop.template-help.com/prestashop_64388/img/p/1/4/7/147-tm_thickbox_default.jpg" data-fancybox-group="other-views" class="fancybox" title="Whole-Spice-Nutmeg-Whole,-1.1-Ounce">
                                <img class="img-responsive" id="thumb_147" src="https://ld-prestashop.template-help.com/prestashop_64388/img/p/1/4/7/147-medium_default.jpg" alt="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" title="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" height="203" width="162" itemprop="image">
                            </a>
                        </li>
                        <li id="thumbnail_148" class="last">
                            <a href="https://ld-prestashop.template-help.com/prestashop_64388/img/p/1/4/8/148-tm_thickbox_default.jpg" data-fancybox-group="other-views" class="fancybox" title="Whole-Spice-Nutmeg-Whole,-1.1-Ounce">
                                <img class="img-responsive" id="thumb_148" src="https://ld-prestashop.template-help.com/prestashop_64388/img/p/1/4/8/148-medium_default.jpg" alt="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" title="Whole-Spice-Nutmeg-Whole,-1.1-Ounce" height="203" width="162" itemprop="image">
                            </a>
                        </li>
                    </ul>
                </div> <!-- end thumbs_list -->
                <a id="view_scroll_right" title="Other views" href="javascript:{}" style="cursor: pointer; opacity: 1; display: block;"></a>
            </div>
            <!-- end views-block -->
            <!-- end thumbnails -->
            <p class="resetimg clear no-print">
          <span id="wrapResetImages" style="display: none;">
            <a href="https://ld-prestashop.template-help.com/prestashop_64388/index.php?id_product=27&amp;controller=product&amp;id_lang=3" data-id="resetImages">
              <i class="icon-redo2"></i>
              Display all pictures
            </a>
          </span>
            </p>
        </div>
        <!-- center infos -->
        <div class="pb-right-column col-xs-12 col-md-6">
            <div class="product-info-line">
                <!-- availability or doesntExist -->
                <p id="availability_statut" style="display: none;">

                    <span id="availability_value" class="label label-success"></span>
                </p>
                <p id="product_reference">
                    <label>Reference: </label>
                    <span class="editable" itemprop="sku" content="00120">00120</span>
                </p>
                <p id="product_condition">
                    <label>Condition: </label>
                    <link itemprop="itemCondition" href="https://schema.org/NewCondition">
                    <span class="editable">New product</span>
                </p>
                <!-- number of item in stock -->
                <p id="pQuantityAvailable">
                    <span id="quantityAvailable">100</span>
                    <span style="display: none;" id="quantityAvailableTxt">Item</span>
                    <span id="quantityAvailableTxtMultiple">Items</span>
                </p>
            </div>
            <p class="warning_inline" id="last_quantities" style="display: none;">Warning: Last items in stock!</p>
            <p id="availability_date" style="display: none;">
                <span id="availability_date_label">Availability date:</span>
                <span id="availability_date_value"></span>
            </p>
            <!-- Out of stock hook -->
            <div id="oosHook" style="display: none;">

            </div>
            <h1 itemprop="name">Whole Spice Nutmeg Whole</h1>
            <span class="new-box no-print">
          <span class="new-label">New</span>
        </span>
            <!-- add to cart form-->
            <form id="buy_block" action="https://ld-prestashop.template-help.com/prestashop_64388/index.php?controller=cart" method="post" target="_top">
                <!-- hidden datas -->
                <p class="hidden">
                    <input type="hidden" name="token" value="411a2115d6a806c8e796d228181406e7">
                    <input type="hidden" name="id_product" value="27" id="product_page_product_id">
                    <input type="hidden" name="add" value="1">
                    <input type="hidden" name="id_product_attribute" id="idCombination" value="577">
                </p>
                <div class="box-info-product">
                    <div class="content_prices clearfix">
                        <!-- prices -->
                        <div class="all-price-info">
                            <p class="our_price_display" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
                                <link itemprop="availability" href="https://schema.org/InStock"><span id="our_price_display" itemprop="price" content="18">$18.00</span><meta itemprop="priceCurrency" content="USD">                  </p>
                            <p id="old_price" class="hidden" style="display: none;"><span id="old_price_display" style="display: none;"><span class="price"></span></span>                  </p>
                            <p id="reduction_percent" class="hidden" style="display:none;"><span id="reduction_percent_display"></span></p>
                            <p id="reduction_amount" style="display:none"><span id="reduction_amount_display"></span></p>
                        </div>
                        <!-- end prices -->




                        <div class="clear"></div>
                    </div> <!-- end content_prices -->
                    <div class="product_attributes clearfix">
                        <!-- attributes -->
                        <div id="attributes">
                            <div class="clearfix"></div>
                            <fieldset class="attribute_fieldset">
                                <label class="attribute_label">Size:&nbsp;</label>
                                <div class="attribute_list">
                                    <ul>
                                        <li>
                                            <input type="radio" class="attribute_radio" name="group_5" value="28" checked="checked">
                                            <label>0.12 oz</label>
                                        </li>
                                        <li>
                                            <input type="radio" class="attribute_radio" name="group_5" value="29">
                                            <label>1 oz.</label>
                                        </li>
                                        <li>
                                            <input type="radio" class="attribute_radio" name="group_5" value="30">
                                            <label>2 oz.</label>
                                        </li>
                                        <li>
                                            <input type="radio" class="attribute_radio" name="group_5" value="31">
                                            <label>4 oz.</label>
                                        </li>
                                    </ul>
                                </div> <!-- end attribute_list -->
                            </fieldset>
                        </div> <!-- end attributes -->
                        <div class="bottom-content clearfix">
                            <!-- quantity wanted -->
                            <p id="quantity_wanted_p">
                                <input type="text" min="1" name="qty" id="quantity_wanted" class="text" value="1">
                                <a href="#" data-field-qty="qty" class="product_quantity_down">
                                    <i class="icon-chevron-down"></i>
                                </a>
                                <a href="#" data-field-qty="qty" class="product_quantity_up">
                                    <i class="icon-chevron-up"></i>
                                </a>
                                <span class="clearfix"></span>
                            </p>
                            <div id="add_to_cart_product_page_button">
                                <p id="add_to_cart" class="no-print">
                                    <button type="submit" name="Submit" class="btn btn-lg btn-primary ajax_add_to_cart_product_button">
                                        <span>Add to cart</span>
                                    </button>
                                </p>
                            </div>
                            <p class="buttons_bottom_block no-print">
                                <a id="wishlist_button_nopop" href="#" onclick="WishlistCart('wishlist_block_list', 'add', '27', $('#idCombination').val(), document.getElementById('quantity_wanted').value); return false;" rel="nofollow" title="В избранное"></a>
                            </p>
                            <p class="buttons_bottom_block no-print">
                                <a href="#" id="collection_button_nopop" onclick="AddProductToCollection('action_add', '27', $('#idCombination').val(), document.getElementById('quantity_wanted').value); return false;" rel="nofollow" title="Добавить в мою коллекцию"></a>
                            </p>
                            <span class="link" id="add_preorder">
    Купить в один клик
  </span>
                            <p class="border"></p>
                            <p class="socialsharing_product no-print">
                                <button data-type="twitter" type="button" class="btn btn-twitter social-sharing"></button>
                                <button data-type="facebook" type="button" class="btn btn-facebook social-sharing"></button>
                                <button data-type="google-plus" type="button" class="btn btn-google-plus social-sharing"></button>
                                <button data-type="pinterest" type="button" class="btn btn-pinterest social-sharing"></button>
                            </p>
                            <!-- Productpaymentlogos module -->
                            <div id="product_payment_logos">
                                <div class="box-security">
                                    <h5 class="product-heading-h5"></h5>
                                    <img src="/prestashop_64388/modules/productpaymentlogos/img/e7edac4b0d27bc56e794471c83f2a347.png" alt="" class="img-responsive">
                                </div>
                            </div>
                            <!-- /Productpaymentlogos module -->
                        </div>
                        <!-- minimal quantity wanted -->
                        <p id="minimal_quantity_wanted_p" style="display: none;">
                            The minimum purchase order quantity for the product is
                            <b id="minimal_quantity_label">1</b>
                        </p>
                    </div> <!-- end product_attributes -->
                </div> <!-- end box-info-product -->
            </form>
        </div>
        <!-- end center infos-->
    </div> <!-- end primary_block -->
</div> <!-- itemscope product wrapper -->


<a href="#" id="ui-to-top" class="ui-to-top icon-chevron-up"></a>