<!-- Footer -->
<footer id="footer">
    <div class="footer-container">

        <div class="wrapper it_BLVMIUELKITB container">
            <div class="row it_JUFPQKVLYQND border-bottom">
                <div class="it_CFZHMUJWOTYI col-xs-12 col-sm-3  col-lg-2 ">
                    <div class="module "><!-- Block categories module -->
                        <section class="blockcategories_footer footer-block">
                            <h4>Категории</h4>
                            <div class="category_footer toggle-footer">
                                <div class="list">
                                    <ul class="tree dhtml">

                                       <?$cats = GetAllGoodCategories();
                                    if(count($cats)>0){
                                        foreach ($cats as $cat){
                                            ?>
                                            <li >
                                            <a   href="/categories/<?=$cat['id']?>" title="<?=$cat['name']?>">
                                                <?=$cat['name']?>
                                            </a>
                                        </li>
                                            <?
                                        }
                                    }?>



                                    </ul>
                                </div>
                            </div> <!-- .category_footer -->
                        </section>
                        <!-- /Block categories module --></div></div>
                <div class="it_MUXIWOMRPMJD col-xs-12 col-sm-3  col-lg-2 ">
                    <div class="module ">  <!-- Block CMS module footer -->
                        <section class="footer-block" id="block_various_links_footer">
                            <h4>Информация</h4>
                            <ul class="toggle-footer">
                                <li class="item">
                                    <a href="/index.php?controller=prices-drop" title="Скидки">
                                        Скидки
                                    </a>
                                </li>
                                <li class="item">
                                    <a href="/index.php?controller=new-products" title="Новые товары">
                                        Новые товары
                                    </a>
                                </li>
                                <li class="item">
                                    <a href="/index.php?controller=stores" title="Наш магазин">
                                        Наш магазин
                                    </a>
                                </li>
                                <li class="item">
                                    <a href="/index.php?controller=contact" title="Свяжитесь с нами">
                                        Свяжитесь с нами
                                    </a>
                                </li>
                                <li class="item">
                                    <a href="/index.php?id_cms=4&amp;controller=cms&amp;id_lang=3" title="About us">
                                        About us
                                    </a>
                                </li>
                                <li class="item">
                                    <a href="/index.php?id_cms=6&amp;controller=cms&amp;id_lang=3" title="Pages configuration">
                                        Pages configuration
                                    </a>
                                </li>
                                <li>
                                    <a href="/index.php?controller=sitemap" title="Карта сайта">
                                        Карта сайта
                                    </a>
                                </li>
                                <li>
                                    <a href="/index.php?fc=module&amp;module=smartblog&amp;controller=category&amp;id_lang=3" title="blog"> blog </a>
                                </li>
                            </ul>

                        </section>
                        <!-- /Block CMS module footer -->
                    </div></div>
                <div class="it_RDDVTKLWPSLH col-xs-12 col-sm-3  col-lg-2 ">
                    <div class="module "><!-- Block myaccount module -->
                        <section class="footer-block">
                            <h4>
                                <a href="/index.php?controller=my-account" title="Управление моей учетной записью" rel="nofollow">Моя учетная запись</a>
                            </h4>
                            <div class="block_content toggle-footer">
                                <ul class="bullet">
                                    <li>
                                        <a href="/index.php?controller=history" title="Мои заказы" rel="nofollow">Мои заказы</a>
                                    </li>
                                    <li>
                                        <a href="/index.php?controller=order-follow" title="Мои возвраты" rel="nofollow">Мои возвраты</a>
                                    </li>
                                    <li>
                                        <a href="/index.php?controller=order-slip" title="Мои платёжные квитанции" rel="nofollow">Мои платёжные квитанции</a>
                                    </li>
                                    <li>
                                        <a href="/index.php?controller=addresses" title="Мои адреса" rel="nofollow">Мои адреса</a>
                                    </li>
                                    <li>
                                        <a href="/index.php?controller=identity" title="Управление моими персональными данными" rel="nofollow">Моя личная информация</a>
                                    </li>

                                </ul>
                            </div>
                        </section>
                        <!-- /Block myaccount module --></div></div>
                <div class="it_DUEUVTDROIOV col-xs-12 col-sm-3   ">
                    <div class="module "><!-- MODULE Block contact infos -->
                        <section id="block_contact_infos" class="footer-block">
                            <div>
                                <h4>Контактная информация</h4>
                                <ul class="toggle-footer">
                                    <li>
                                        <i class="icon-map-marker"></i>
                                        <span>
            My Company
                          , 4578 Marmora Road, Glasgow D04 89GR
                      </span>
                                    </li>
                                    <li>
                                        <i class="icon-telephone"></i>
                                        <span>
            Звоните нам:
            <a href="tel:0123-456-789">
              0123-456-789
            </a>
          </span>
                                    </li>
                                    <li>
                                        <i class="icon-envelope-open"></i>
                                        <span>
            E-mail:
            <a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;%69%6e%66%6f@%64%65%6d%6f%6c%69%6e%6b.%6f%72%67" >&#x69;&#x6e;&#x66;&#x6f;&#x40;&#x64;&#x65;&#x6d;&#x6f;&#x6c;&#x69;&#x6e;&#x6b;&#x2e;&#x6f;&#x72;&#x67;</a>
          </span>
                                    </li>
                                </ul>
                            </div>
                        </section>
                        <!-- /MODULE Block contact infos --></div></div>
                <div class="it_ORXARWXZVGDM col-xs-12   col-lg-3 offset-5">
                    <div class="row it_CQYQBCJUEZYP ">
                        <div class="it_UWKLLFFMGSTQ col-xs-12 col-sm-5  col-lg-12 ">
                            <div class="module "><section id="social_block" class="footer-block">
                                    <h4>Подпишитесь на наши обновления</h4>
                                    <ul class="toggle-footer">
<!--                                        <li class="fa fa-odnoklassniki">-->
<!--                                            <a target="_blank" href="https://ok.ru/group/53985378369685" title="Одноклассники">-->
<!--                                                <span>Одноклассники</span>-->
<!--                                            </a>-->
<!--                                        </li>-->
                                        <li class="facebook">
                                            <a target="_blank" href="https://www.facebook.com/TemplateMonster/" title="Facebook">
                                                <span>Facebook</span>
                                            </a>
                                        </li>
                                        <li class="twitter">
                                            <a target="_blank" href="https://twitter.com/TemplateMonster" title="Twitter">
                                                <span>Twitter</span>
                                            </a>
                                        </li>
                                        <li class="youtube">
                                            <a target="_blank" href="https://www.youtube.com/user/TemplateMonsterCo" title="Youtube">
                                                <span>Youtube</span>
                                            </a>
                                        </li>
                                        <li class="google-plus">
                                            <a target="_blank" href="https://plus.google.com/+TemplateMonster" title="Google+" rel="publisher">
                                                <span>Google+</span>
                                            </a>
                                        </li>
                                        <li class="instagram">
                                            <a class="_blank" href="https://www.instagram.com/template_monster/">
                                                <span>Instagram</span>
                                            </a>
                                        </li>
                                    </ul>
                                </section>
                                <div class="clearfix"></div></div></div>
                        <div class="it_TMQMKDKHVBLL col-xs-12 col-sm-7  col-lg-12 offset-4">
                            <div class="module "><!-- Block Newsletter module-->
                                <div id="newsletter_block_left" class="footer-block">
                                    <h4>Рассылка</h4>
                                    <div class="toggle-footer">
                                        <form action="//ld-prestashop.template-help.com/prestashop_64388/index.php" method="post">
                                            <div class="form-group" >
                                                <input class="inputNew form-control grey newsletter-input" id="newsletter-input" type="text" name="email" size="18" value="Введите ваш e-mail" autocomplete="off" />
                                                <button type="submit" name="submitNewsletter" class="btn btn-primary btn-md">
                                                    <span>Подписаться</span>
                                                </button>
                                                <input type="hidden" name="action" value="0" />
                                            </div>
                                        </form>
                                    </div>

                                </div>
                                <!-- /Block Newsletter module-->
                            </div></div></div></div></div>
            <div class="row it_MIDXBTBXZKTL ">
                <div class="it_KRMNKERTYKPH col-xs-12 col-sm-6   ">
                    <div class="bottom-footer">
                        <a class="_blank" href="http://www.prestashop.com"> © 2018 - Ecommerce software by PrestaShop™ </a>
                    </div>
                </div>
                <div class="it_ENLDJZOFFCQN col-xs-12 col-sm-6   text-right">
                    <div class="module ">
                        <!-- Block payment logo module -->
                        <div id="paiement_logo_block_left" class="paiement_logo_block">
                            <a href="/index.php?id_cms=1&amp;controller=cms&amp;id_lang=3">
                                <img src="/themes/finik/layout/html/themes/theme1430/img/logo_paiement_visa.png" alt="visa" width="41" height="15" />
                                <img src="/themes/finik/layout/html/themes/theme1430/img/logo_american_express.png" alt="visa" width="58" height="15" />
                                <img src="/themes/finik/layout/html/themes/theme1430/img/logo_paiement_mastercard.png" alt="mastercard" width="78" height="15" />
                                <img src="/themes/finik/layout/html/themes/theme1430/img/logo_paiement_paypal.png" alt="paypal" width="54" height="15" />
                            </a>
                        </div>
                        <!-- /Block payment logo module --></div></div></div></div>
        <div class="row it_IWLMMOOTZPGS ">
            <div class="it_MPUIITUBPWSM col-xs-12    ">
                <div class="module "></div>
                <div class="module "></div>
                <div class="module "></div>
                <div class="module "></div>
                <div class="module "></div>
                <div class="module ">
                    <!-- begin olark code -->
                    <script data-cfasync="false" type='text/javascript'>
                        /*<![CDATA[*/window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){
                            f[z]=function(){
                                (a.s=a.s||[]).push(arguments)};var a=f[z]._={
                            },q=c.methods.length;while(q--){(function(n){f[z][n]=function(){
                                f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={
                                0:+new Date};a.P=function(u){
                                a.p[u]=new Date-a.p[0]};function s(){
                                a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){
                                hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){
                                return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){
                                b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{
                                b.contentWindow[g].open()}catch(w){
                                c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{
                                var t=b.contentWindow[g];t.write(p());t.close()}catch(x){
                                b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({
                            loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});

                        /* custom configuration goes here (www.olark.com/documentation) */

                        olark.identify('7830-582-10-3714');



                        /*]]>*/</script>
                    <!-- end olark code --></div></div></div>
    </div>
</footer>
<!-- #footer -->