<header id="header">




    <div class="wrapper it_WEVEUPFXEPYV container">
        <div class="row it_CEOANIIGZSWC align-center border-bottom">
            <div class="it_CFEJHWGZAMAS col-xs-12  col-md-3  ">
                <div id="header_logo">
                    <a href="/" title="<?=$sk['title'];?>">
                        <img class="logo img-responsive" src="/themes/finik/layout/assets/img/logo3.jpg" alt="<?=$sk['title'];?>" width="158" height="57"/>
                    </a>
                </div>
            </div>
            <div class="it_QTKIAMBNAEGQ col-xs-12  col-md-9  align-right">
                <div class="row it_WMHMXRCCVRRD compare-link"></div>
                <div class="module ">

                    <a href="/" title="Моё избранное" class="wishlist-link">
                        Избранное
                    </a></div>
                <div class="module ">
                    <div id="header-login">
                        <div class="current tm_header_user_info">
                            <a href="#" onclick="return false;">
                                Войти на сайт
                            </a>
                        </div>
                    </div>

                </div>
                <div class="module "><!-- MODULE Block cart -->
                    <div class="cartBox clearfix">
                        <div class="shopping_cart">
                            <a href="javascript:ShowGoodCart();" title="Просмотр корзины" rel="nofollow">
                                <b>Корзина:</b>
                                <span class="ajax_cart_quantity unvisible">0</span>
                                <span class="ajax_cart_total unvisible">
              </span>
                                <span class="ajax_cart_no_product">0</span>
                            </a>
                            <div class="cart_block block">
                                <div class="block_content">
                                    <!-- block list of products -->
                                    <div class="cart_block_list">
                                        <p class="cart_block_no_products">
                                            Нет товаров
                                        </p>
                                        <div class="cart-prices">
                                            <div class="cart-prices-line first-line  unvisible">
                <span>
                  Доставка:
                </span>
                                                <span class="cart_block_shipping_cost ajax_cart_shipping_cost">
                                      Определить                                  </span>
                                            </div>
                                            <div class="cart-prices-line last-line">
                                                <span>Итого, к оплате</span>:
                                                <span class="price cart_block_total ajax_block_cart_total">$0.00</span>
                                            </div>
                                        </div>
                                        <p class="cart-buttons">
                                            <a id="button_order_cart" class="btn btn-default btn-md" href="/index.php?controller=order" title="Оформить заказ" rel="nofollow">
                <span>
                  Оформить заказ
                </span>
                                            </a>
                                        </p>
                                    </div>
                                </div>
                            </div><!-- .cart_block -->
                        </div>
                    </div>

                    <div id="layer_cart">
                        <div class="layer_cart_product">
                            <span class="cross" title="Закрыть окно"></span>
                            <span class="title">
        Товар добавлен в корзину
      </span>
                            <div class="product-image-container layer_cart_img">
                            </div>
                            <div class="layer_cart_product_info">
                                <span id="layer_cart_product_title" class="product-name"></span>
                                <span id="layer_cart_product_attributes"></span>
                                <div>
                                    <span>Количество:</span>
                                    <span id="layer_cart_product_quantity"></span>
                                </div>
                                <div>
                                    <span>Итого, к оплате:</span>
                                    <span id="layer_cart_product_price"></span>
                                </div>
                            </div>
                        </div>
                        <div class="layer_cart_cart">
      <span class="title">
        <!-- Plural Case [both cases are needed because page may be updated in Javascript] -->
        <span class="ajax_cart_product_txt_s  unvisible">
          Товаров в корзине: <span class="ajax_cart_quantity">0</span>.
        </span>
          <!-- Singular Case [both cases are needed because page may be updated in Javascript] -->
        <span class="ajax_cart_product_txt ">
          Сейчас в корзине 1 товар.
        </span>
      </span>

                            <div class="layer_cart_row">
                                <strong class="dark">
                                    Стоимость
                                </strong>
                                <span class="ajax_block_products_total">
                  </span>
                            </div>

                            <div class="layer_cart_row  unvisible">
                                <strong class="dark">
                                    Стоимость доставки&nbsp;        </strong>
                                <span class="ajax_cart_shipping_cost">
                       Определить                  </span>
                            </div>
                            <div class="layer_cart_row">
                                <strong class="dark">
                                    Итого, к оплате
                                </strong>
                                <span class="ajax_block_cart_total">
                  </span>
                            </div>
                            <div class="button-container">
        <span class="continue btn btn-default btn-md" title="Продолжить покупки">
          <span>
            Продолжить покупки
          </span>
        </span>
                                <a class="btn btn-primary btn-md" href="/index.php?controller=order" title="Оформить заказ" rel="nofollow">
          <span>
            Оформить заказ
          </span>
                                </a>
                            </div>
                        </div>
                        <div class="crossseling"></div>
                    </div> <!-- #layer_cart -->
                    <div class="layer_cart_overlay"></div>

                    <!-- /MODULE Block cart --></div>
                <div class="module "><!-- Block languages module -->
                    <div id="languages-block-top" class="languages-block">
                        <div class="current">
                            <span>Русский</span>
                        </div>
                        <ul id="first-languages" class="languages-block_ul toogle_content">
                            <li >
                                <a href="/index.php?live_configurator=&amp;header_layout=129&amp;top_layout=141&amp;home_layout=135&amp;footer_layout=123&amp;theme=&amp;product_footer_layout=&amp;id_lang=1" title="English (United States)" rel="alternate" hreflang="en">
                                    <span>English</span>
                                </a>
                            </li>
                            <li >
                                <a href="/index.php?live_configurator=&amp;header_layout=129&amp;top_layout=141&amp;home_layout=135&amp;footer_layout=123&amp;theme=&amp;product_footer_layout=&amp;id_lang=2" title="Deutsch (German)" rel="alternate" hreflang="de">
                                    <span>Deutsch</span>
                                </a>
                            </li>
                            <li class="selected">
                                <span>Русский</span>
                            </li>
                            <li >
                                <a href="/index.php?live_configurator=&amp;header_layout=129&amp;top_layout=141&amp;home_layout=135&amp;footer_layout=123&amp;theme=&amp;product_footer_layout=&amp;id_lang=4" title="Español (Spanish)" rel="alternate" hreflang="es">
                                    <span>Español</span>
                                </a>
                            </li>
                            <li >
                                <a href="/index.php?live_configurator=&amp;header_layout=129&amp;top_layout=141&amp;home_layout=135&amp;footer_layout=123&amp;theme=&amp;product_footer_layout=&amp;id_lang=5" title="Français (French)" rel="alternate" hreflang="fr">
                                    <span>Français</span>
                                </a>
                            </li>
                            <li >
                                <a href="/index.php?live_configurator=&amp;header_layout=129&amp;top_layout=141&amp;home_layout=135&amp;footer_layout=123&amp;theme=&amp;product_footer_layout=&amp;id_lang=6" title="עברית (Hebrew)" rel="alternate" hreflang="he">
                                    <span>עברית</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- /Block languages module --></div>
                <div class="module "><!-- Block currencies module -->
                    <div id="currencies-block-top">
                        <form id="setCurrency" action="/prestashop_64388/?live_configurator&amp;header_layout=129&amp;top_layout=141&amp;home_layout=135&amp;footer_layout=123&amp;live_configurator&amp;theme=&amp;header_layout=129&amp;top_layout=141&amp;home_layout=135&amp;footer_layout=123&amp;product_footer_layout=" method="post">
                            <div class="current">
                                <input type="hidden" name="id_currency" id="id_currency" value=""/>
                                <input type="hidden" name="SubmitCurrency" value="" />
                                <span>USD</span>                                </div>
                            <ul id="first-currencies" class="currencies_ul toogle_content">
                                <li class="selected">
                                    <a href="javascript:setCurrency(1);" rel="nofollow" title="Dollar (USD)">
                                        Dollar (USD)
                                    </a>
                                </li>
                                <li >
                                    <a href="javascript:setCurrency(2);" rel="nofollow" title="Euro (EUR)">
                                        Euro (EUR)
                                    </a>
                                </li>
                            </ul>
                        </form>
                    </div>
                    <!-- /Block currencies module --></div></div></div>
        <div class="row it_HLVVPKPUDIQB stick-up">
            <div class="it_ZQGROVYODDWH col-xs-12  col-md-10  position-static">
                <div class="module ">
                    <div class="top_menu top-level tmmegamenu_item">
                        <div class="menu-title tmmegamenu_item">Меню</div>
                        <ul class="menu clearfix top-level-menu tmmegamenu_item">


                            <li class=" top-level-menu-li tmmegamenu_item it_07471156">
                                <a class="it_07471156 top-level-menu-li-a tmmegamenu_item" href="/">Главная</a>
                            </li>

                            <li class=" top-level-menu-li tmmegamenu_item it_07471156">
                                <a class="it_07471156 top-level-menu-li-a tmmegamenu_item" href="/blog">Блог</a>
                            </li>



                        </ul>
                    </div>
                </div></div>
            <div class="it_LFXDPFEMJMON col-xs-12  col-md-2  position-static">
                <div class="module "><div id="tmsearch">
                        <form id="tmsearchbox" method="get" action="/index.php?fc=module&amp;module=tmsearch&amp;controller=tmsearch&amp;id_lang=3" >
                            <input type="hidden" name="fc" value="module" />
                            <input type="hidden" name="controller" value="tmsearch" />
                            <input type="hidden" name="module" value="tmsearch" />
                            <input type="hidden" name="orderby" value="position" />
                            <input type="hidden" name="orderway" value="desc" />
                            <select name="search_categories" class="form-control">
                                <option  value="2">Все категории</option>
                                <option  value="12">--BBQ &amp; Grilling</option>
                                <option  value="24">---Pork</option>
                                <option  value="29">----Adobo</option>
                                <option  value="30">----Baharat</option>
                                <option  value="31">----BBQ Rub - Fin &amp; Feather</option>
                                <option  value="25">---Beef</option>
                                <option  value="32">----Asian Cajun Beef</option>
                                <option  value="33">----Bar-H Beef Rub</option>
                                <option  value="34">----BBQ Rub - KC Tailgater&#039;s</option>
                                <option  value="26">---Chiken</option>
                                <option  value="35">----BBQ Rub - Memphis Beale St.</option>
                                <option  value="36">----BBQ Rub - Smoky</option>
                                <option  value="37">----BBQ Rub - Tarheel</option>
                                <option  value="27">---Fish</option>
                                <option  value="38">----Calico Fish Rub</option>
                                <option  value="39">----Creole Spice</option>
                                <option  value="40">----Thai Seasoning</option>
                                <option  value="28">---Lamb</option>
                                <option  value="41">----Anatolian Lamb Rub</option>
                                <option  value="42">----BBQ Rub - Yucatan Rojo</option>
                                <option  value="43">----Biscayne Citrus Rub</option>
                                <option  value="13">--Salts</option>
                                <option  value="44">---Black Lava Flake Salt</option>
                                <option  value="45">---Kosher Salt</option>
                                <option  value="46">---Truffle Salt</option>
                                <option  value="47">---Smoked Sea Salt Flakes</option>
                                <option  value="48">---Himalayan Pink Salt</option>
                                <option  value="14">--Baking</option>
                                <option  value="15">--All-Purpose</option>
                                <option  value="16">--Cheese &amp; Dips</option>
                                <option  value="17">--Chiles</option>
                                <option  value="18">--Cinnamon</option>
                                <option  value="19">--Curry</option>
                                <option  value="20">--Exotics</option>
                            </select>
                            <input class="tm_search_query form-control" type="text" id="tm_search_query" name="search_query" placeholder="Поиск..." value="" />
                            <button type="submit" name="tm_submit_search" class="button-search">
                                <span>Поиск</span>
                            </button>
                        </form>
                        <span id="search-toggle"></span>
                        <span class="search-close"></span>
                    </div></div></div></div></div>
    <div class="row it_CJZJWRVYQPRQ ">
        <div class="it_YOWQZEGYYEZR col-xs-12    ">
            <div class="module "></div>
            <div class="module "></div></div></div>

    <form method="post" action="/index.php?controller=products-comparison" class="compare-form">
        <button type="submit" class="bt_compare">
            <span>Сравнить</span>
        </button>
        <input type="hidden" name="compare_product_count" class="compare_product_count" value="0" />
        <input type="hidden" name="compare_product_list" class="compare_product_list" value="" />
    </form>


</header>