<style>
    .table_price {
        border-collapse: collapse;
        border-left: 3px solid #fba919;
        border-right: 3px solid #fba919;
        border-bottom: 3px solid #fba919;
        font-family: "Lucida Grande", sans-serif;
    }
    .table_price caption {
        background: #fba919;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
        padding: 10px;
        box-shadow: 0 2px  4px 0 rgba(0,0,0,.3);
        color: white;
        font-family: "Roboto Slab",serif;
        font-style: normal;
        font-size: 26px;
        text-align: center;
        margin: 0;
        text-decoration: underline;
    }
    .table_price td, .table_price th {
        padding: 10px;
    }
    .table_price th {
        text-align: left;
        font-size: 18px;
    }
    /*.table_price tr:nth-child(2n) {*/
        /*background: #E5E5E5;*/
    /*}*/
    .table_price td:last-of-type {
        text-align: center;
    }
    .table_price a {
        display: inline-block;
        padding: 5px 10px;
        background: #fba919;
        box-shadow: 2px 2px 0 0 #a22800;
        position: relative;
    }
    .table_price a:hover {
        box-shadow: none;
        top: 2px;
        left: 2px;
    }
    .table_price tr td span{
        position: absolute;
        width: auto;
        font-size: 10px;
        padding-bottom: 4px;
    }
    
     .table_price caption span{
         font-weight: 800;
         text-decoration: none;
    }

     .open_i{
         background: #f37318  !important;
     }
    
    
    TABLE,TH,TD{border:1px solid black;border-collapse:collapse;}
</style>

<section class="constructo-aboutUs-area section-padding" >
    <div class="container">
        <div class="row">
            <div class="col-xs-12 text-center">
                <div class="section-title">
                    <h2>Цены</h2>
                    <p>Цены без учета сложности выполнения работ</p>
                    <div class="line">
                        <img src="/themes/penotep4/layout/img/line.png" alt="<?=$_SERVER['SERVER_NAME'];?>">
                    </div>
                </div>
            </div>
        </div>






        <div class="row padding-top">
            <div class="col-md-12">




                            <div class="section-title text-center">
                                <h2>За 1 м²</h2>
                            </div>


                <div class="table-responsive">
                    <table class="table_price table">
                        <caption>Закрытая ячейка <span>слой 30 мм</span></caption>

                        <tr>
                            <td>Плотность DOW</td>
                            <td>До 300 м²</td>
                            <td>От 300 м²</td>
                            <td>Более 1000 м²</td>
                        </tr>

                        <tr>
                            <td>35-40 кг/м³</td>
                            <td>450 руб./м²</td>
                            <td>425 руб./м²</td>
                            <td>Договорная</td>
                        </tr>

                        <tr>
                            <td>35-40 кг/м³ &nbsp;(в условиях низкой температуры)</td>
                            <td >500 руб./м²</td>
                            <td >475 руб./м²</td>
                            <td>Договорная</td>
                        </tr>
                    </table>
                </div><div class="table-responsive">
                    <table class="table_price table">
                        <caption>Закрытая ячейка <span>слой 50 мм</span></caption>

                        <tr>
                            <td>Плотность DOW</td>
                            <td>До 300 м²</td>
                            <td>От 300 м²</td>
                            <td>Более 1000 м²</td>
                        </tr>

                        <tr>
                            <td>35-40 кг/м³</td>
                            <td>750 руб./мм²</td>
                            <td>725 руб./м²</td>
                            <td>Договорная</td>
                        </tr>

                        <tr>
                            <td>35-40 кг/м³ &nbsp;(в условиях низкой температуры)</td>
                            <td >800 руб./м²</td>
                            <td >775 руб./м²</td>
                            <td>Договорная</td>
                        </tr>
                    </table>
                </div><div class="table-responsive">
                    <table class="table_price table">
                        <caption>Закрытая ячейка <span>слой 70 мм</span></caption>

                        <tr>
                            <td>Плотность DOW</td>
                            <td>До 300 м²</td>
                            <td>От 300 м²</td>
                            <td>Более 1000 м²</td>
                        </tr>

                        <tr>
                            <td>35-40 кг/м³</td>
                            <td>1050 руб./м²</td>
                            <td>1025 руб./м²</td>
                            <td>Договорная</td>
                        </tr>

                        <tr>
                            <td>35-40 кг/м³ &nbsp;(в условиях низкой температуры)</td>
                            <td >1100 руб./м²</td>
                            <td >1075 руб./м²</td>
                            <td>Договорная</td>
                        </tr>
                    </table>


</div><div class="table-responsive">


                    <table class="table_price table">
                        <caption class="open_i">Открытая ячейка <span>слой 30 мм</span></caption>
                        <tr>
                            <td>Плотность DOW</td>
                            <td>До 300 м²</td>
                            <td>От 300 м²</td>
                            <td>Более 1000 м²</td>
                        </tr>

                        <tr>
                            <td>10-15 кг/м³</td>
                            <td>275 руб./м²</td>
                            <td>250 руб./м²</td>
                            <td>Договорная</td>
                        </tr>
                    </table>
                </div><div class="table-responsive">
                    <table class="table_price table">
                        <caption class="open_i">Открытая ячейка <span>слой 50 мм</span></caption>
                        <tr>
                            <td>Плотность DOW</td>
                            <td>До 300 м²</td>
                            <td>От 300 м²</td>
                            <td>Более 1000 м²</td>
                        </tr>

                        <tr>
                            <td>10-15 кг/м³</td>
                            <td>325 руб./м²</td>
                            <td>300 руб./м²</td>
                            <td>Договорная</td>
                        </tr>
                    </table>
                </div><div class="table-responsive">
                    <table class="table_price table">
                        <caption class="open_i">Открытая ячейка <span>слой 70 мм</span></caption>
                        <tr>
                            <td>Плотность DOW</td>
                            <td>До 300 м²</td>
                            <td>От 300 м²</td>
                            <td>Более 1000 м²</td>
                        </tr>

                        <tr>
                            <td>10-15 кг/м³</td>
                            <td>400 руб./м²</td>
                            <td>475 руб./м²</td>
                            <td>Договорная</td>
                        </tr>
                    </table>

                </div>

                            <div class="section-title text-center">
                                <h2>За 1 м³</h2>
                            </div>


                <div class="table-responsive">
                    <table class="table_price table">
                        <caption class="">Закрытая ячейка <span></span></caption>
                        <tr>
                            <td>Плотность DOW</td>
                            <td>До 15 м³</td>
                            <td>От 50 м³</td>
                            <td>Более 100 м³</td>
                        </tr>

                        <tr>
                            <td>35-40 кг/м³</td>
                            <td>14000 руб./м³</td>
                            <td>13500 руб./м³</td>
                            <td>Договорная</td>
                        </tr>
                        <tr>
                            <td>35-40 кг/м³ &nbsp;(в условиях низкой температуры)</td>
                            <td>15000 руб./м³</td>
                            <td>14500 руб./м³</td>
                            <td>Договорная</td>
                        </tr>
                    </table>
                </div>

                <div class="table-responsive">
                    <table class="table_price table">
                        <caption class="open_i">Открытая ячейка <span></span></caption>
                        <tr>
                            <td>Плотность DOW</td>
                            <td>До 15 м³</td>
                            <td>От 50 м³</td>
                            <td>Более 100 м³</td>
                        </tr>

                        <tr>
                            <td>10-15 кг/м³</td>
                            <td>5500 руб./м³</td>
                            <td>5000 руб./м³</td>
                            <td>Договорная</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>