
<!DOCTYPE HTML>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="ru-ru"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8 ie7" lang="ru-ru"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9 ie8" lang="ru-ru"><![endif]-->
<!--[if gt IE 8]> <html class="no-js ie9" lang="ru-ru"><![endif]-->
<html lang="ru-ru">
<?=SK_getPage("elements/head");?>
<body id="index" class="index hide-left-column hide-right-column lang_ru  one-column">
<!--[if IE]>
<div class="old-ie">
    <a href="http://windows.microsoft.com/en-US/internet-explorer/..">
        <img src="/themes/finik/layout/html/themes/theme1430/img/ie8-panel/warning_bar_0000_us.jpg" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."/>
    </a>
</div>
<![endif]-->
<span id="page-preloader"></span>
<div id="page">


    <?=SK_getPage("elements/header")?>


    <?=$sk['content'];?>
    <?=SK_getPage("elements/footer")?>
    <?=SK_getPage("elements/modals")?>

</div><!-- #page -->
</body>



</html>