
<!DOCTYPE html>
<html lang="en">

<?=SK_getPage("elements/head");?>
<div id="preloader"></div>
<body class="js">
<?=SK_getPage("elements/header");?>



<section class="constructo-footer-top section-padding">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 text-center">
                <div class="footer-top-content">
                    <h2>Ошибка 404! Данной страницы не существует, либо она была удалена.</h2>
                    <p>Если вам нужен материал с этой страницы, свяжитесь с нами, мы поможем вам найти ответы на все вопросы по теме ППУ</p>
                    <a href="#" class="contat-usf">CONTACT US</a>
                    <a href="#" class="learn-moref">LEARN MORE</a>
                </div>
            </div>
        </div>
    </div>
</section>



<section class="constructo-features-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-3 text-center">
                <div class="single-features">
                    <div class="features-icon">
                        <img src="/themes/penotep4/layout/img/con1.png" class="ficon3" alt="theconstructo.com">
                        <div class="ficonh">
                            <img src="/themes/penotep4/layout/img/con1h.png" alt="theconstructo.com">
                        </div>
                    </div>
                    <h4>АДРЕС</h4>
                    <p>г. Люберцы MO Улица Электрофикации д. 2 Б</p>
                    <p>Россия</p>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <div class="single-features">
                    <div class="features-icon">
                        <img src="/themes/penotep4/layout/img/con2.png" class="ficon3" alt="theconstructo.com">
                        <div class="ficonh">
                            <img src="/themes/penotep4/layout/img/con2h.png" alt="theconstructo.com">
                        </div>
                    </div>
                    <h4>ТЕЛЕФОНЫ</h4>
                    <p>Phone : +7 (999) 999-99-99</p>
                    <p>Mobile : +7 (999) 999-99-99</p>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <div class="single-features">
                    <div class="features-icon">
                        <img src="/themes/penotep4/layout/img/con3.png" class="ficon3" alt="theconstructo.com">
                        <div class="ficonh">
                            <img src="/themes/penotep4/layout/img/con3h.png" alt="theconstructo.com">
                        </div>
                    </div>
                    <h4>E-MAIL</h4>
                    <p>support@penotep.ru</p>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <div class="single-features">
                    <div class="features-icon">
                        <img src="/themes/penotep4/layout/img/con4.png" class="ficon3" alt="theconstructo.com">
                        <div class="ficonh">
                            <img src="/themes/penotep4/layout/img/con4h.png" alt="theconstructo.com">
                        </div>
                    </div>
                    <h4>ЧАСЫ РАБОТЫ</h4>
                    <p>Ежедневно : 8:00 - 21:00</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="constructo-contactUs-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 text-center">
                <div class="section-title">
                    <h2>ОСТАВИТЬ ЗАЯВКУ</h2>
                    <p>Оставьте заявку на сайте, и мы тут же перезвоним Вам для уточнения деталей.</p>
                    <div class="line">
                        <img src="/themes/penotep4/layout/img/linew.png" alt="">
                    </div>
                </div>
            </div>
        </div>
        <div class="row padding-top">
            <div class="col-sm-5">
                <div class="google-map-area">
                    <div class="googlemap" id="gmap">
                    </div>
                </div>
            </div>
            <div class="col-sm-7">
                <div class="contact-form">
                    <form action="#">
                        <input type="text" placeholder="Name" class="single-input">
                        <input type="text" placeholder="Email" class="single-input">
                        <input type="text" placeholder="Subject" class="single-input">
                        <textarea placeholder="Message" class="single-input"></textarea>
                        <input type="submit" class="submit" value="ОСТАВИТЬ ЗАЯВКУ">
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>






<div class="constructo-copyright">
    <div class="scroll-top">
        <a href="#" class="top0 fa fa-angle-up"></a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="footer-link">
                    <a href="#" class="fa fa-facebook"></a>
                    <a href="#" class="fa fa-twitter"></a>
                    <a href="#" class="fa fa-google-plus"></a>
                    <a href="#" class="fa fa-feed"></a>
                    <a href="#" class="fa fa-linkedin"></a>
                    <a href="#" class="fa fa-skype"></a>
                    <a href="#" class="fa fa-vimeo"></a>
                    <a href="#" class="fa fa-tumblr"></a>
                </div>
            </div>
            <div class="col-sm-6 text-right">
                <div class="footer-text">
                    <p> Пенотеп © Все права защищены </p>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA5zlr4THd1YwuZNLk4HmR59EsFBCYnnFg"></script>
<!-- jquery min js -->

<!-- jquery waypoints -->
<script src="/themes/penotep4/layout/js/waypoints.min.js"></script>
<!-- jquery easing js -->
<script src="/themes/penotep4/layout/js/jquery.easing.1.3.js"></script>
<!-- rippler js -->
<script src="/themes/penotep4/layout/js/jquery.rippler.min.js"></script>
<!-- bootstra js -->
<script src="/themes/penotep4/layout/js/bootstrap.min.js"></script>
<!-- jquery nav js -->
<script src="/themes/penotep4/layout/js/jquery.nav.js"></script>
<!-- jquery sticky js -->
<script src="/themes/penotep4/layout/js/jquery.sticky.js"></script>
<!-- slick js -->
<script src="/themes/penotep4/layout/slick/slick.min.js"></script>
<!-- jquery counter up -->
<script src="/themes/penotep4/layout/js/jquery.counterup.min.js"></script>
<!-- jqeury isotop filtaring plugins -->
<script src="/themes/penotep4/layout/js/isotope.pkgd.min.js"></script>
<!-- jquery magnifiq popup    -->
<script src="/themes/penotep4/layout/js/jquery.magnific-popup.min.js"></script>
<!-- parallax -->
<script src="/themes/penotep4/layout/js/parallax.min.js"></script>
<!-- jquery active js -->
<script src="/themes/penotep4/layout/js/gmap.js"></script>
<script src="/themes/penotep4/layout/js/active.js"></script>
</body>

</html>
